# Generated by Django 5.1.1 on 2024-09-08 06:38

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=inventory.models.generate_item_code, editable=False, max_length=20, unique=True),
        ),
    ]
